const fs=require('fs');
const path=require('path');
const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/cnhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const pages=['index','about','facilities','services','class-schedule','membership','locations','blog'];
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage();const errors=[];const layouts=[];const interactions=[];const linkIssues=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 const popupPage=await browser.newPage();
 await popupPage.setViewportSize({width:390,height:844});await popupPage.goto('http://127.0.0.1:4173/index.html');await popupPage.waitForTimeout(450);
 assert.equal(await popupPage.locator('[data-reload-promo]').isVisible(),true);assert.equal(await popupPage.locator('input[name="fullName"]').getAttribute('placeholder'),'Họ và tên');
 await popupPage.keyboard.press('Escape');assert.equal(await popupPage.locator('[data-reload-promo]').isVisible(),false);assert.equal(await popupPage.evaluate(()=>sessionStorage.getItem('reloadPromoClosed')),'true');assert.equal(await popupPage.evaluate(()=>document.body.classList.contains('modal-open')),false);
 const validationPage=await browser.newPage();await validationPage.setViewportSize({width:1024,height:768});await validationPage.goto('http://127.0.0.1:4173/about.html');await validationPage.waitForTimeout(450);
 await validationPage.getByRole('button',{name:'ĐĂNG KÝ',exact:true}).click();assert.equal(await validationPage.locator('#reload-promo-branch-error').isVisible(),true);assert.equal(await validationPage.locator('#reload-promo-full-name-error').isVisible(),true);assert.equal(await validationPage.locator('#reload-promo-phone-error').isVisible(),true);
 await validationPage.locator('#reload-promo-branch').selectOption('reload-women');await validationPage.locator('#reload-promo-full-name').fill('Nguyễn Văn A');await validationPage.locator('#reload-promo-phone').fill('12');await validationPage.locator('#reload-promo-email').fill('email-invalid');await validationPage.getByRole('button',{name:'ĐĂNG KÝ',exact:true}).click();assert.equal(await validationPage.locator('#reload-promo-phone-error').isVisible(),true);assert.equal(await validationPage.locator('#reload-promo-email-error').isVisible(),true);
 await validationPage.locator('#reload-promo-phone').fill('0909 123 456');await validationPage.locator('#reload-promo-email').fill('example@email.com');await validationPage.getByRole('button',{name:'ĐĂNG KÝ',exact:true}).click();assert.equal(await validationPage.locator('[data-reload-promo-success]').isVisible(),true);assert.equal(await validationPage.locator('[data-reload-promo-form]').isHidden(),true);assert.equal(await validationPage.evaluate(()=>sessionStorage.getItem('reloadPromoClosed')),'true');await validationPage.getByRole('button',{name:'ĐÓNG',exact:true}).click();assert.equal(await validationPage.evaluate(()=>document.body.classList.contains('modal-open')),false);
 const bmiPage=await browser.newPage();await bmiPage.setViewportSize({width:1440,height:900});await bmiPage.goto('http://127.0.0.1:4173/index.html');await bmiPage.waitForTimeout(450);await bmiPage.locator('[data-reload-promo-close]').first().click();
 const bmiForm=bmiPage.locator('[data-bmi-form]');await bmiForm.getByRole('button',{name:'TÍNH BMI'}).click();assert.equal(await bmiPage.locator('#bmi-height-error').isVisible(),true);assert.equal(await bmiPage.locator('#bmi-weight-error').isVisible(),true);
 await bmiPage.locator('#bmi-height').fill('0');await bmiPage.locator('#bmi-weight').fill('-1');await bmiForm.getByRole('button',{name:'TÍNH BMI'}).click();assert.match(await bmiPage.locator('#bmi-height-error').textContent(),/100/);assert.match(await bmiPage.locator('#bmi-weight-error').textContent(),/25/);
 await bmiPage.locator('#bmi-height').fill('170');await bmiPage.locator('#bmi-weight').fill('65');await bmiForm.getByRole('button',{name:'TÍNH BMI'}).click();assert.equal(await bmiPage.locator('[data-bmi-value]').textContent(),'22.5');assert.equal(await bmiPage.locator('[data-bmi-status]').textContent(),'Bình thường');assert.equal(await bmiPage.locator('[data-bmi-result]').isVisible(),true);interactions.push('BMI: required/range validation and 170cm/65kg = 22.5 Bình thường');await bmiPage.close();
 const responsiveViewports=[[2560,1440],[1920,1080],[1536,864],[1440,900],[1366,768],[1280,720],[1024,768],[820,1180],[768,1024],[844,390],[812,375],[430,932],[414,896],[390,844],[375,812],[360,800],[360,740],[320,568],[1366,600],[1024,600],[667,375]];
 const responsivePage=await browser.newPage();responsivePage.on('pageerror',e=>errors.push(e.message));responsivePage.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
 for(const [width,height] of responsiveViewports){
  await responsivePage.setViewportSize({width,height});await responsivePage.goto('http://127.0.0.1:4173/index.html');await responsivePage.waitForTimeout(450);
  const responsiveState=await responsivePage.evaluate(()=>{const promo=document.querySelector('[data-reload-promo]');const modal=promo.querySelector('.reload-promo__modal').getBoundingClientRect();const close=promo.querySelector('[data-reload-promo-close]').getBoundingClientRect();const content=promo.querySelector('.reload-promo__content');return {scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyLocked:document.body.classList.contains('modal-open'),modal:{left:modal.left,right:modal.right,top:modal.top,bottom:modal.bottom},close:{left:close.left,right:close.right,top:close.top,bottom:close.bottom},contentScrollable:content.scrollHeight>content.clientHeight+1,columns:getComputedStyle(promo.querySelector('.reload-promo__fields-row')).gridTemplateColumns,visible:getComputedStyle(promo).display!=='none'};});
  assert.equal(responsiveState.visible,true,`${width}x${height}: popup visible`);assert.equal(responsiveState.scrollWidth,responsiveState.clientWidth,`${width}x${height}: horizontal overflow`);assert.equal(responsiveState.bodyLocked,true,`${width}x${height}: body scroll lock`);assert.ok(responsiveState.modal.left>=0&&responsiveState.modal.right<=width+1&&responsiveState.modal.top>=0&&responsiveState.modal.bottom<=height+1,`${width}x${height}: modal bounds`);assert.ok(responsiveState.close.left>=0&&responsiveState.close.right<=width+1&&responsiveState.close.top>=0&&responsiveState.close.bottom<=height+1,`${width}x${height}: close bounds`);if(width<=767&&width<height)assert.equal(responsiveState.columns.split(' ').length,1,`${width}x${height}: mobile form stack`);await responsivePage.locator('[data-reload-promo-close]').first().click();assert.equal(await responsivePage.evaluate(()=>document.body.classList.contains('modal-open')),false);await responsivePage.evaluate(()=>sessionStorage.removeItem('reloadPromoClosed'));
 }
 await responsivePage.setViewportSize({width:390,height:844});await responsivePage.goto('http://127.0.0.1:4173/index.html');await responsivePage.waitForTimeout(450);assert.equal(await responsivePage.locator('[data-reload-promo]').isVisible(),true);await responsivePage.setViewportSize({width:844,height:390});await responsivePage.waitForTimeout(100);const orientationState=await responsivePage.evaluate(()=>{const r=document.querySelector('.reload-promo__modal').getBoundingClientRect();return {scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,bodyLocked:document.body.classList.contains('modal-open'),bounds:{left:r.left,right:r.right,top:r.top,bottom:r.bottom}}});assert.equal(orientationState.scrollWidth,orientationState.clientWidth);assert.equal(orientationState.bodyLocked,true);assert.ok(orientationState.bounds.left>=0&&orientationState.bounds.right<=844&&orientationState.bounds.top>=0&&orientationState.bounds.bottom<=390);await responsivePage.locator('[data-reload-promo-close]').first().click();interactions.push(`promo: responsive matrix (${responsiveViewports.length} viewports), no overflow and orientation change`);await responsivePage.close();
 interactions.push('promo: auto-open, Escape, sessionStorage, validation and success state');await popupPage.close();await validationPage.close();
 fs.mkdirSync(__dirname+'/qa/multipage',{recursive:true});
 for(const name of pages){
  for(const [width,height] of [[1920,1080],[1440,900],[1366,768],[1024,768],[768,1024],[430,932],[390,844]]){
   await page.setViewportSize({width,height});await page.goto(`http://127.0.0.1:4173/${name}.html`);
   await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>{i.loading='eager';return i.decode().catch(()=>{});}));});
   if(name==='index'&&width===1440){await page.waitForTimeout(400);assert.equal(await page.locator('[data-reload-promo]').isVisible(),true);await page.locator('[data-reload-promo-close]').first().click();assert.equal(await page.locator('[data-reload-promo]').isVisible(),false);}
   const state=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,brokenImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src),duplicateIds:[...document.querySelectorAll('[id]')].map(e=>e.id).filter((id,i,a)=>a.indexOf(id)!==i),active:[...document.querySelectorAll('nav a[aria-current="page"]')].map(a=>a.getAttribute('href')),h1:document.querySelectorAll('h1').length}));
   layouts.push({page:name,...state});
   if(width===1440||width===390)await page.screenshot({path:`${__dirname}/qa/multipage/${name}-${width}.png`,fullPage:true});
   assert.equal(state.scrollWidth,width,`${name} overflow at ${width}`);assert.equal(state.brokenImages.length,0);assert.equal(state.duplicateIds.length,0);assert.deepEqual(state.active,[name+'.html']);assert.equal(state.h1,1);
   if(width===390){await page.getByRole('button',{name:'Mở menu điều hướng'}).click();assert.equal(await page.locator('#navigation').isVisible(),true);assert.equal(await page.locator('#navigation a').count(),8);await page.keyboard.press('Escape');assert.equal(await page.locator('#navigation').isVisible(),false);interactions.push(name+': mobile menu and Escape');}
  }
  const links=await page.locator('a[href]').evaluateAll(nodes=>nodes.map(a=>a.getAttribute('href')));
  for(const href of links){if(/^(https?:|mailto:|tel:)/.test(href))continue;const [file,hash]=href.split('#');const target=file||name+'.html';if(!fs.existsSync(path.join(__dirname,target))){linkIssues.push(`${name}: ${href}`);continue;}if(hash&&!new RegExp(`id=["']${hash}["']`).test(fs.readFileSync(path.join(__dirname,target),'utf8')))linkIssues.push(`${name}: missing anchor ${href}`);}
  if(name==='index'){assert.equal(await page.locator('.container.testimonials.page-section').count(),0,'index: testimonials removed');assert.equal(await page.locator('.glance').count(),0,'index: glance removed');assert.equal(await page.locator('.why').count(),0,'index: why removed');}
  if(name==='about'){assert.equal(await page.locator('.glance').count(),1,'about: glance retained');assert.equal(await page.locator('.why').count(),1,'about: why retained');}
  if(name==='about'){const first=await page.locator('.testimonial-card').first().textContent();await page.getByRole('button',{name:'Đánh giá tiếp theo'}).click();assert.notEqual(await page.locator('.testimonial-card').first().textContent(),first);await page.getByRole('button',{name:'Đánh giá trước'}).click();assert.equal(await page.locator('.testimonial-card').first().textContent(),first);interactions.push(name+': testimonial next/previous');}
  if(name==='class-schedule'){for(const day of ['Thứ 2','Thứ 3','Thứ 4','Thứ 5','Thứ 6','Thứ 7','Chủ nhật']){await page.getByRole('tab',{name:day,exact:true}).click();assert.equal(await page.getByRole('tab',{name:day,exact:true}).getAttribute('aria-selected'),'true');assert.ok(await page.locator('.class-row').count()>=4);}await page.getByRole('tab',{name:'Chủ nhật',exact:true}).press('ArrowRight');assert.equal(await page.getByRole('tab',{name:'Thứ 2',exact:true}).getAttribute('aria-selected'),'true');await page.locator('.book-button').first().click();assert.equal(await page.locator('#info-dialog').isVisible(),true);await page.keyboard.press('Escape');interactions.push('schedule: seven days, keyboard wrap, booking dialog');}
  await page.locator('.search-toggle').click();await page.locator('#site-search').fill('gói tập');assert.equal(await page.locator('#search-results a').getAttribute('href'),'membership.html');await page.keyboard.press('Escape');
 }
 assert.deepEqual(errors,[]);assert.deepEqual(linkIssues,[]);
 const home=layouts.find(l=>l.page==='index'&&l.width===1440);
 const result={oldHomeHeight:3178,newHomeHeight:home.height,homeLengthPercent:Math.round(home.height/3178*100),layouts,errors,linkIssues,interactions};
 fs.writeFileSync(__dirname+'/qa/multipage/results.json',JSON.stringify(result,null,2));console.log(JSON.stringify({homeLengthPercent:result.homeLengthPercent,newHomeHeight:home.height,layouts:layouts.length,errors,linkIssues,interactions},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
