const fs=require('fs'),path=require('path');const out='qa/body-visualizer-actual-vs-simulation-precommit/';
const entries=[];const add=(category,file,reason,replacement,action)=>entries.push({category,file,reason,replacement,action});
add('A','qa/body-visualizer-regression.cjs','State utility, eight-site-page layout, header/footer, menu/search assertions remain valid.','legacy-site-results.json','Only local port and report destination changed; all56 layout assertions executed.');
add('A','qa/body-visualizer-measurement-guidance-bmi/run-qa.cjs','Guidance/BMI/icon semantics and responsive checks remain valid.','legacy-guidance/functional-regression.json','Output folder and explicit allowed candidate+QA paths updated; functional assertions unchanged and PASS.');
add('B','qa/body-visualizer.test.cjs','Old 82.0 display string is now actual82; gender section is inside the already-existing disclosure.','legacy-body-visualizer-results.json','Updated presentation selector/value plus port/output only; all viewer, touch, context, fallback and navigation assertions retained and PASS.');
add('B','qa/measurement-constraints-phase1.cjs','Old rejection of calibrated-range overflow, exact endpoints in actual state, million-step model sliders, Height girth rewriting, rounded actual precision, Weight200 rejection conflict with approved product contract.','contract.cjs; regression-results.json; legacy-parity.json','Migrated entrypoint to comprehensive replacement suite; exact original preserved in legacy-originals. No passing assertion removed without replacement category below.');
add('B','qa/measurement-constraints-phase1-ux-fix/run-browser.cjs','Actual108.2 must stay108.2, explicit invalid150 correction uses product140, Height confirmation preserves75.9/62.9/84.4 instead of new model minima.','legacy-ux-fix/browser-results.json','Updated only these expectations and local/output wiring; BMI pending, null slider, model count and responsive assertions retained; PASS.');
add('B','qa/weight-ux/tests.mjs','180.1 is valid now; maximum product Weight is200.','legacy-weight-unit.json','Invalid fixture changed to200.1; valid200 added;20 assertions PASS.');
for(const name of ['body-calibrated-mapping','hip-production-integration','height-production-integration'])add('B',`qa/${name}/tests.mjs`,'Raw calibration support does not imply product acceptance. Calibration sample weights/interpolation/clamps must remain unchanged.',name+'-unit.json','Preserved calibration assertions; validateMeasurement expectation explicitly uses product bands. Older pre-Height/Hip nongeometry exclusions replaced by Weight/Inseam/Gender invariance plus positive Height/Hip geometry checks. Original files preserved. Body calibration loader now merges the existing separate hip dataset. PASS.');
const c=[
['measurement-constraints-phase1-ui-review/run-ui-review.cjs','Historical UI capture expects near-limit badge, invalid just-outside model draft, endpoint writeback, Height girth adjustment and rejected Weight200.','contract.cjs aliases/invalid/Height/nongeometry/reset/Goal; legacy-ux-fix; guidance'],
['weight-ux/run.cjs','Pre-sample-default contract expects invalid drafts to blank BMI/Height, reset nulls, Height140 accepted and data-height-clamp.','contract.cjs BMI/state/null/reset; parity.mjs; lifecycle.cjs'],
['weight-ux/responsive.cjs','Historical presentation uses retired clamp/helper containers.','responsive-regression.json; legacy-guidance'],
['ux-phase1/run.cjs','Pre-sample-default reset, old field-only clamps and old fixed stage dimensions are superseded; input associations and navigation still required.','contract.cjs; legacy-guidance; touch.cjs; body-visualizer.test.cjs'],
['ux-phase2/run.cjs','Old fixed520/480 stage and1024 sticky assumptions precede current stacked presentation; recorded historical hashes refer to that earlier version.','touch.cjs390/768 preserves relevant return-focus/contact/keyboard behaviors; lifecycle.cjs identity. Historical110-cycle stress not claimed rerun.'],
['body-calibrated-mapping/browser.js','Pre-Height/Hip integration browser fixture assumes base-plane mapping and sample-neutral reset.','parity.mjs; migrated mapping unit; contract.cjs'],
['hip-production-integration/browser.js','Pre-Height browser calibration samples omit Height baseline drift and expect old target set.','parity.mjs; migrated hip/Height unit; contract.cjs'],
['hip-production-integration/run-browser.cjs','Launcher for historical browser.js above.','Same replacement as browser.js'],
['hip-production-integration/controller-tests.mjs','Old removed hip-scale targets and reset topology are a historical controller contract, independent of actual/simulation.','Existing unchanged controller/GLB hashes;1094 Height/controller unit checks; runtime19-target checks'],
['height-production-integration/browser.js','Old raw-full-precision/no-rounding browser contract, null Height neutral reset and Height140 accepted predate model-range validation.','parity.mjs independently evaluates immediate legacy contract; migrated1094 raw mapping/controller checks; contract.cjs'],
['height-production-integration/run.cjs','Launcher for historical Height browser contract.','Same replacement as browser.js'],
['height-production-integration/responsive.cjs','Old runner changes Height without applying pending transaction, so endpoint screenshots would be mislabeled.','contract.cjs transitions/responsive; lifecycle.cjs'],
['body-visualizer-production-v5-audit/_runtime-audit-runner.cjs','Historical V5 audit snapshots direct scene-bound state and model-domain inputs; not the new acceptance oracle.','contract.cjs network/bounds; protected-hashes.json; legacy-parity.json'],
['body-morph-integration-browser.js','Historical production morph/geometry audit before current Height and input policy.','Unchanged protected model stack; migrated raw mapping tests; current browser contract']];
for(const [p,why,repl]of c)add('C','qa/'+p,why,repl,'Historical source retained unchanged; explicitly superseded, not executed as a current acceptance test.');
const all=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name).replaceAll('\\','/');if(e.isDirectory()){if(!p.includes('actual-vs-simulation-precommit'))walk(p);}else if(/\.(cjs|mjs|js)$/.test(p))all.push(p);}}walk('qa');
const known=new Set(entries.map(e=>e.file));const other=all.filter(p=>!known.has(p));for(const file of other)add('D',file,/actual-vs-simulation-implementation/.test(file)?'New architecture evidence, not a legacy test.':/v16|iter03|axilla|height-range|height-edge|height-full|height-rnd|phase2|production-morph|calibration|hip-measurement/.test(file)?'R&D/calibration/reporting asset or historical model harness; outside this product-input migration.':'Site-specific unrelated test, reporting/extraction helper, fixture or infrastructure; not a model-range input acceptance oracle.','Unchanged unless explicitly listed in executed suites.','Retained; not claimed executed.');
const counts=Object.fromEntries(['A','B','C','D'].map(c=>[c,entries.filter(e=>e.category===c).length]));fs.writeFileSync(out+'legacy-test-migration.json',JSON.stringify({counts,unit:'source entrypoint/helper file (not individual assertions)',entries,assertionMigration:{unchanged:['19 targets/one canvas/model request','draft retention/malformed inputs','BMI committed actual formula','independent Goal','null optional semantics','nongeometry Weight/Inseam','reset approved samples','camera/touch/context/homepage'],changed:['calibrated overflow invalid → product-valid accepted and bounded derived value','actual canonical endpoint → actual literal plus exact mappingValue','model-domain million-step slider → product native0.1','Height confirm rewrites girths → preserves girths','round actual precision → preserve actual, round mappingValue','Weight180.1 invalid → Weight200.1 invalid'],replaced:['near-limit badge → neutral support-range text','old null-default reset → approved sample reset','old pre-Height/Hip exclusions → assert geometric Height/Hip, keep Weight/Inseam nongeometry']}},null,2));
fs.writeFileSync(out+'legacy-test-inventory.md','# Legacy test inventory\n\nFull recursive inventory of QA JavaScript sources. A/B/C are the23 relevant legacy entrypoints; D contains other files and new architecture evidence. Counts are source files, not assertions. Original modified sources are preserved in `legacy-originals/`. Historical C suites are explicitly superseded; their old assertions are not silently marked passing.\n\n'+Object.entries(counts).map(([c,n])=>`${c}: ${n}`).join(' · ')+'\n\nA = STILL VALID UNCHANGED (assertions; local/output plumbing may change). B = EXPECTATION MUST CHANGE. C = OBSOLETE / REPLACED. D = UNRELATED to this migration.\n\n'+entries.map(e=>`## ${e.category} — ${e.file}\n\n${e.reason}\n\nAction: ${e.action}\n\nCoverage: ${e.replacement}\n`).join('\n'));console.log(counts);
