import fs from 'node:fs';import cp from 'node:child_process';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import path from 'node:path';
import {compileCalibration,calibratedFields,mapMeasurements} from '../../assets/js/body-visualizer/normalization.js';
import {deriveSimulation,deriveSceneState} from '../../assets/js/body-visualizer/simulation-values.js';
import {validateDraft} from '../../assets/js/body-visualizer/measurement-constraints.js';
import {defaults,createState} from '../../assets/js/body-visualizer/state.js';
const base=path.resolve('assets/js/body-visualizer');const source=cp.execFileSync('git',['show','HEAD:assets/js/body-visualizer/measurement-constraints.js'],{encoding:'utf8'}).replace(/from '\.\/([^']+)'/g,(_,file)=>`from '${pathToFileURL(path.join(base,file)).href}'`);const legacy=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const profiles=compileCalibration({...JSON.parse(fs.readFileSync('qa/body-measurement-calibration/measurements.json')),...JSON.parse(fs.readFileSync('qa/hip-measurement-calibration/measurements.json'))});
const cases=[],excluded=[];let maxMappingValueDifference=0,maxInfluenceDifference=0;
for(const height of [151.2,160,165,170,180,190,194.6]){const lh=legacy.normalizeMeasurement(legacy.validateDraft('height',height).value,legacy.heightLimits);for(const key of Object.keys(calibratedFields)){const range=legacy.supportedRange(key,lh,profiles);for(const raw of [range.min,range.max,...Object.values(legacy.displayedRange(range)),...profiles[key].samples.map(s=>range.neutral+s.cm-profiles[key].base)]){const oldValidation=legacy.validateDraft(key,raw,{height:lh,profiles});if(!oldValidation.valid)continue;if(!validateDraft(key,raw).valid){excluded.push({key,height,raw,reason:'Intentional product band differs from old model band; mapping remains tested in raw calibration suites.'});continue;}
const oldValue=legacy.normalizeMeasurement(oldValidation.value,range);const actual={...defaults,height,[key]:raw};const sim=deriveSimulation(actual,profiles);const oldBody={...actual,height:lh};for(const field of Object.keys(calibratedFields))if(oldBody[field]!=null)oldBody[field]=legacy.normalizeMeasurement(oldBody[field],legacy.supportedRange(field,lh,profiles));oldBody[key]=oldValue;
const mappingDifference=Math.abs(oldValue-sim.sceneBody[key]);maxMappingValueDifference=Math.max(maxMappingValueDifference,mappingDifference);assert.equal(mappingDifference,0);
for(const mode of ['current','goal','compare']){const state={...createState(),mode,currentBody:actual,goalBody:{...actual}},derived=deriveSceneState(state,profiles);assert.deepEqual(derived.currentBody,derived.goalBody);const a=mapMeasurements(oldBody,profiles).weights,b=mapMeasurements(derived.currentBody,profiles).weights;for(const name of Object.keys(a)){maxInfluenceDifference=Math.max(maxInfluenceDifference,Math.abs(a[name]-b[name]));assert.equal(a[name],b[name]);}}
cases.push({key,height,raw,mappingValue:oldValue,pass:true});}}}
const result={pass:true,legacySource:'git HEAD:measurement-constraints.js evaluated independently',cases:cases.length,maxMappingValueDifference,maxInfluenceDifference,excluded,casesDetail:cases};fs.writeFileSync('qa/body-visualizer-actual-vs-simulation-precommit/legacy-parity.json',JSON.stringify(result,null,2));console.log({cases:cases.length,maxMappingValueDifference,maxInfluenceDifference});
