const fs=require('fs'),assert=require('node:assert/strict');const {chromium}=require('C:/Users/cnhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const out='qa/body-visualizer-actual-vs-simulation-precommit/';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),r={pass:true,checks:[],errors:[],warnings:[]};try{for(const width of [390,768]){const context=await browser.newContext({viewport:{width,height:width===390?844:1024},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await context.newPage();p.on('pageerror',e=>r.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')r.errors.push(m.text());if(m.type()==='warning')r.warnings.push(m.text());});await p.addInitScript(()=>sessionStorage.setItem('reloadPromoClosed','true'));await p.goto('http://127.0.0.1:4175/body-visualizer.html');await p.waitForSelector('[data-viewer="ready"]');const snap=()=>p.evaluate(async()=> (await import('/assets/js/body-visualizer/app.js')).inspectVisualizer());const note=name=>r.checks.push({width,name,pass:true});
await p.locator('.bv-stage').scrollIntoViewIfNeeded();await p.waitForTimeout(150);const b=await p.locator('.bv-stage').boundingBox(),cdp=await context.newCDPSession(p),x=b.x+b.width/2,y=b.y+b.height/2;
let before=await snap();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+65,y:y+15}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notDeepEqual((await snap()).viewer.camera,before.viewer.camera);note('touch rotation changes camera');
before=await snap();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y},{x:x+25,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-55,y},{x:x+55,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notDeepEqual((await snap()).viewer.camera,before.viewer.camera);note('pinch zoom changes camera');
for(const view of ['side','back','reset']){await p.locator('[data-view="'+view+'"]').tap();assert.equal(await p.locator('[data-view="'+(view==='reset'?'front':view)+'"]').getAttribute('aria-pressed'),'true');}note('camera controls');
await p.locator('.bv-advanced>summary').tap();await p.locator('#bv-thigh').tap();await p.locator('#bv-thigh').fill('72');assert.equal((await snap()).state.currentBody.thigh,72);assert.equal((await snap()).inputs.thigh.invalid,false);await p.locator('[data-field="thigh"] summary').tap();assert(await p.locator('#bv-thigh-help').isVisible());await p.locator('[data-field="thigh"] summary').tap();
await p.locator('[data-range="thigh"]').scrollIntoViewIfNeeded();const slider=await p.locator('[data-range="thigh"]').boundingBox();await p.touchscreen.tap(slider.x+slider.width*.2,slider.y+slider.height/2);const s=await snap();assert(s.state.currentBody.thigh>=40&&s.state.currentBody.thigh<=75);assert.notEqual(s.state.currentBody.thigh,72);assert(Math.abs(s.state.currentBody.thigh*10-Math.round(s.state.currentBody.thigh*10))<1e-8);note('mobile form + helper + native touch slider');
await p.locator('#bv-waist').tap();await p.locator('#bv-waist').fill('120');await p.setViewportSize({width,height:480});await p.locator('[data-model-inline]').waitFor({state:'visible'});before=await snap();await p.locator('[data-model-inline]').tap();await p.locator('[data-model-return]').waitFor({state:'visible'});await p.setViewportSize({width,height:width===390?844:1024});await p.waitForTimeout(300);await p.locator('[data-model-return]').tap();await p.waitForFunction(()=>document.activeElement?.dataset.field==='waist');assert.deepEqual((await snap()).state,before.state);assert.notEqual(await p.evaluate(()=>document.activeElement.type),'number');note('coarse pointer inline viewer / form return preserves actual');
await p.locator('#bv-weight').fill('60');await p.locator('.bv-stage').focus();await p.locator('[data-field="waist"]').evaluate(e=>scrollTo(0,scrollY+e.getBoundingClientRect().top-180));await p.locator('[data-model-quick]').waitFor({state:'visible'});await p.locator('[data-floating-contact-toggle]').tap();assert(await p.locator('.floating-contact').evaluate(e=>e.classList.contains('is-open')));assert(await p.locator('[data-model-quick]').isHidden());await p.locator('[data-floating-contact-toggle]').tap();await p.locator('[data-model-quick]').waitFor({state:'visible'});note('floating contact suppresses/reinstates model utility');
await p.screenshot({path:out+'screenshots/touch-'+width+'.png'});assert.equal((await snap()).viewer.rendererCanvasCount,1);assert.equal((await snap()).viewer.webglError,0);await context.close();}
assert.deepEqual(r.errors,[]);assert.deepEqual(r.warnings,[]);
}catch(e){r.pass=false;r.error=e.stack;process.exitCode=1;}finally{await browser.close();fs.writeFileSync(out+'touch-regression.json',JSON.stringify(r,null,2));console.log(JSON.stringify(r,null,2));}})();
