const fs=require('fs'),assert=require('node:assert/strict');
const {chromium}=require('C:/Users/cnhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),requests=[],errors=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>sessionStorage.setItem('reloadPromoClosed','true'));
const dir='qa/body-visualizer-actual-vs-simulation-implementation/',write=(name,x)=>fs.writeFileSync(dir+name+'.json',JSON.stringify(x,null,2));
await page.goto('http://127.0.0.1:4175/body-visualizer.html');await page.waitForSelector('[data-viewer="ready"]');
const inspect=()=>page.evaluate(async()=> (await import('/assets/js/body-visualizer/app.js')).inspectVisualizer());
const open=async()=>page.locator('.bv-advanced').evaluate(e=>e.open=true);
const shot=async(name)=>{await page.locator('.bv-stage').scrollIntoViewIfNeeded();await page.waitForTimeout(450);await page.screenshot({path:dir+'screenshots/'+name+'.png',fullPage:true});};
const fill=async(key,value)=>{await page.locator('#bv-'+key).fill(String(value));assert.equal(await page.locator('#bv-'+key).getAttribute('aria-invalid'),'false');};
await open();await shot('fully-supported');
for(const [key,value] of [['thigh',72],['arm',48],['waist',120]]){await fill(key,value);const x=await inspect();assert.equal(x.state.currentBody[key],value);assert.equal(x.simulation.current.fields[key].simulationStatus,'ABOVE_SIMULATION_RANGE');await shot(key+value+'-H165');}
await fill('height',205);let x=await inspect();assert.equal(x.state.currentBody.height,165);assert(x.pendingHeight);await page.locator('[data-apply-height]').click();x=await inspect();assert.equal(x.state.currentBody.height,205);assert.equal(x.state.currentBody.thigh,72);assert.equal(x.simulation.current.simulationHeight,194.6037856625685);assert.equal(await page.locator('[data-bmi]').textContent(),'14.3');await shot('height205');
await fill('height',160);await page.locator('[data-cancel-height]').click();assert.equal((await inspect()).state.currentBody.height,205);
await fill('height',165);await page.locator('[data-apply-height]').click();await page.locator('[data-next]').click();x=await inspect();assert.equal(x.state.goalBody.thigh,72);assert.equal(x.state.goalBody.calf,null);await open();await fill('thigh',75);await page.locator('[data-next]').click();assert.match(await page.locator('[data-differences]').textContent(),/\+3\.0/);await shot('compare72-75');
await page.locator('#bv-split').fill('30');assert.equal(await page.locator('.bv-divider').evaluate(e=>e.style.left),'30%');for(const view of ['side','back','reset'])await page.locator('[data-view="'+view+'"]').click();
await page.locator('[data-reset]').click();await page.locator('.bv-reset-dialog').getByRole('button',{name:'Khôi phục',exact:true}).click();x=await inspect();assert.equal(x.state.goalBody,null);assert.equal(x.pendingHeight,null);assert.deepEqual(x.drafts,{current:{},goal:{}});
await open();await page.locator('.bv-reference').evaluate(e=>e.open=true);
for(const [key,value] of [['chest',140],['waist',150],['hip',145],['shoulder',48],['arm',50],['thigh',75],['calf',50],['weight',200],['inseam',110]])await fill(key,value);
await page.locator('#bv-thigh').fill('76');x=await inspect();assert.equal(x.state.currentBody.thigh,75);assert.equal(x.inputs.thigh.invalid,true);await fill('thigh',72);
const products=[];for(const [key,values] of Object.entries({thigh:[40,46.9,52,61.5,68,72,75],arm:[18,28,38,45,48,50],waist:[55,72,83,100,120,150],chest:[70,88,108,120,140],height:[145,151.2,165,194.6,205]}))for(const value of values){await fill(key,value);if((await inspect()).pendingHeight)await page.locator('[data-apply-height]').click();const v=await inspect();assert.equal(v.state.currentBody[key],value);products.push({key,value,simulation:v.simulation.current.fields[key]});}
await page.locator('[data-range="thigh"]').focus();await page.keyboard.press('ArrowLeft');assert.equal((await inspect()).state.currentBody.thigh,74.9);
const layouts=[];for(const width of [1440,1280,1024,768,430,390,375]){await page.setViewportSize({width,height:950});await page.locator('#bv-thigh').scrollIntoViewIfNeeded();const size=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert(size.scrollWidth<=width);layouts.push({...size,pass:true});await shot('responsive-'+width);}
x=await inspect();assert.equal(x.viewer.rendererCanvasCount,1);assert.equal(Object.keys(x.viewer.meshes[0].dictionary).length,19);assert.equal(requests.filter(u=>u.endsWith('male-mpfb-production-morph-v5-candidate.glb')).length,1);assert(!requests.some(u=>/v16|iter03|corrective/i.test(u)));assert.deepEqual(errors,[]);
write('responsive-qa',{pass:true,layouts});write('runtime-smoke',{pass:true,errors,V5Requests:1,morphCount:19,V16Requests:0,ITER03Requests:0,corrective:false,products,viewer:x.viewer,checks:['all inputs','actual preservation','height confirm/cancel','BMI actual','goal exact copy/null','compare +3','split','camera buttons','reset','invalid draft','keyboard slider','one canvas']});console.log('Runtime and responsive PASS');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
