import {inspectVisualizer} from '../../assets/js/body-visualizer/app.js';
import {loadCalibration} from '../../assets/js/body-visualizer/normalization.js';
import {heightInfluenceToCm,baselinesAtHeight,HEIGHT_BASE_CM,HEIGHT_TARGET} from '../../assets/js/body-visualizer/height-calibration.js';
import {morphPairs} from '../../assets/js/body-visualizer/morph-controller.js';
import * as T from '../../assets/vendor/three/three.module.min.js';
import {locate,measure,mean} from '../body-measurement-calibration/geometry.js';
const $=s=>document.querySelector(s),snap=()=>inspectVisualizer(),viewer=()=>snap().viewer,delay=ms=>new Promise(r=>setTimeout(r,ms));
const report={checks:[],roundTrips:[],baselines:[],samples:[],edges:[],stress:[]};
const assert=(condition,name)=>{report.checks.push({name,pass:!!condition});if(!condition)throw Error(name);},close=(a,b,t=1e-9)=>Math.abs(a-b)<=t;
function input(key,value){const el=$('#bv-'+key);if(!el)throw Error('Missing input '+key);el.value=value==null?'':String(value);el.dispatchEvent(new Event('input',{bubbles:true}));}
async function settle(){for(let i=0;i<300;i++){await delay(10);if(viewer()&&!viewer().animating&&!viewer().pendingFrame)return;}throw Error('Renderer did not settle');}
function geometry(){const g=inspectVisualizer({includeGeometry:true}).geometry[0];return {...g,points:g.vertices.map(p=>new T.Vector3(...p))};}
function height(g){return (Math.max(...g.points.map(p=>p.y))-Math.min(...g.points.map(p=>p.y)))*100;}
function invariant(){const v=viewer(),m=v.meshes[0],d=m.dictionary,w=m.influences;return m.phenotypePreserved&&m.scale.every(x=>x===1)&&Object.values(morphPairs).every(p=>w[d[p+'-incr']]>=0&&w[d[p+'-incr']]<=1&&w[d[p+'-decr']]>=0&&w[d[p+'-decr']]<=1&&!(w[d[p+'-incr']]&&w[d[p+'-decr']]))&&w[d[HEIGHT_TARGET]]>=-.3&&w[d[HEIGHT_TARGET]]<=.3&&v.webglError===0;}
function quality(g,base){let degenerate=0,rotated=0,minAreaRatio=Infinity;const a=new T.Vector3(),b=new T.Vector3(),c=new T.Vector3(),d=new T.Vector3();for(let i=0;i<g.index.length;i+=3){const [x,y,z]=g.index.slice(i,i+3);a.subVectors(g.points[y],g.points[x]);b.subVectors(g.points[z],g.points[x]);a.cross(b);c.subVectors(base.points[y],base.points[x]);d.subVectors(base.points[z],base.points[x]);c.cross(d);if(a.length()<1e-12)degenerate++;if(c.length()>1e-12){minAreaRatio=Math.min(minAreaRatio,a.length()/c.length());if(a.dot(c)<0)rotated++;}}return {finite:g.vertices.flat().every(Number.isFinite),degenerate,rotatedNormals:rotated,minAreaRatio};}
async function reset(){ $('[data-reset]').click();$('.bv-reset-dialog button[value="reset"]').click();await delay(20);await settle();}
try{
 for(let i=0;i<200&&!viewer();i++)await delay(50);assert(!!viewer(),'viewer ready');$('.bv-stage').scrollIntoView({block:'center'});await settle();
 const profiles=await loadCalibration(),keys=Object.keys(profiles),lm=await(await fetch('/qa/body-measurement-calibration/landmarks.json')).json(),hip=await(await fetch('/qa/hip-measurement-calibration/landmarks.json')).json(),dataset=await(await fetch('/qa/height-full-range/baseline-dataset.json')).json();
 function locations(g){const loc=locate(g.points,lm.mapping),ids=hip.mapping.hips.map(a=>a.index);loc.hips={indices:ids,center:mean(ids.map(i=>g.points[i])).toArray(),normal:[0,1,0],fixedAtBaseline:true};return loc;}
 function neutral(){for(const k of keys)input(k,'');}
 report.initial=snap();assert(Object.keys(viewer().meshes[0].dictionary).length===19,'exactly 19 targets');await reset();const baseline=geometry(),initial=viewer(),identity=v=>[v.modelId,v.sceneId,v.rendererId,...v.geometryIds],ids=identity(initial);
 for(const cm of [151.21778195689558,155,160,165,170,HEIGHT_BASE_CM,175,180,185,190,194.6037856625685,140,200]){input('height',cm);await settle();const debug=viewer().mappingDebug.currentHeight,measured=height(geometry()),error=Math.abs(measured-debug.clampedCm);report.roundTrips.push({requestedCm:cm,clampedCm:debug.clampedCm,influence:viewer().appliedHeight,measuredCm:measured,errorCm:error});assert(error<1e-9&&invariant(),'Height roundtrip '+cm);assert(snap().state.currentBody.height===cm,'raw Height preserved '+cm);}
 for(const h of [-.3,-.2,-.1,0,.1,.2,.3]){neutral();input('height',heightInfluenceToCm(h));await settle();const g=geometry(),loc=locations(g),expected=dataset.samples.find(s=>s.heightInfluence===h).baselines;for(const [key,p] of Object.entries(profiles)){const actual=measure(p.measurement,g.points,g.index,loc[p.measurement]);report.baselines.push({h,field:key,measuredCm:actual.cm,expectedCm:expected[p.measurement],errorCm:Math.abs(actual.cm-expected[p.measurement])});assert(actual.valid&&close(actual.cm,expected[p.measurement],1e-6),'baseline '+h+' '+key);input(key,expected[p.measurement]);}await settle();assert(keys.every(k=>viewer().currentWeights[k]===0),'baseline-neutral inputs '+h);assert(geometry().points.every((p,i)=>p.distanceTo(g.points[i])<1e-12),'neutral geometry '+h);}
 for(const h of [-.3,0,.3]){neutral();input('height',heightInfluenceToCm(h));await settle();const loc=locations(geometry()),base=baselinesAtHeight(h);for(const [field,p] of Object.entries(profiles)){for(const sample of p.samples){const requested=base[p.measurement]+sample.cm-p.base;input(field,requested);await settle();const g=geometry(),actual=measure(p.measurement,g.points,g.index,loc[p.measurement]),error=actual.cm===null?null:Math.abs(actual.cm-requested);report.samples.push({h,field,requestedCm:requested,equivalentCm:viewer().mappingDebug.current[field].equivalentBaseHeightMeasurement,expectedWeight:sample.weight,actualWeight:viewer().currentWeights[field],measuredCm:actual.cm,errorCm:error});assert(close(viewer().currentWeights[field],sample.weight),'sample weight '+h+' '+field+' '+sample.weight);assert(actual.valid&&error<.1,'sample measured geometry '+h+' '+field+' '+sample.weight);assert(invariant(),'sample invariant');}input(field,'');await settle();}}
 const edgeSpecs={A:{h:-.3,weights:Object.fromEntries(keys.map(k=>[k,-1]))},B:{h:-.3,weights:Object.fromEntries(keys.map(k=>[k,1]))},C:{h:.3,weights:Object.fromEntries(keys.map(k=>[k,-1]))},D:{h:.3,weights:Object.fromEntries(keys.map(k=>[k,1]))},E:{h:-.3,weights:{chest:1,waist:-1,hip:1}},F:{h:.3,weights:{chest:-1,waist:1,hip:-1}}};
 async function edge(name){neutral();const e=edgeSpecs[name],base=baselinesAtHeight(e.h);input('height',heightInfluenceToCm(e.h));for(const [k,w] of Object.entries(e.weights)){const p=profiles[k];input(k,base[p.measurement]+(w<0?p.min:p.max)-p.base);}await settle();return e;}
 for(const name of Object.keys(edgeSpecs)){const e=await edge(name),q=quality(geometry(),baseline);report.edges.push({name,...e,quality:q,heightCm:height(geometry()),weights:viewer().currentWeights});assert(q.finite&&q.degenerate===0&&invariant(),'edge stable '+name);assert(Object.entries(e.weights).every(([k,w])=>close(viewer().currentWeights[k],w)),'edge weights '+name);}
 await reset();input('height',180);input('weight',80);await settle();assert($('[data-bmi]').textContent==='24.7','BMI 180/80');const beforeWeight=viewer().meshes[0].influences;input('weight',90);await settle();assert($('[data-bmi]').textContent==='27.8','BMI Weight update');assert(JSON.stringify(beforeWeight)===JSON.stringify(viewer().meshes[0].influences),'Weight no deformation');input('height',9999);await settle();assert(viewer().appliedHeight===0&&snap().state.currentBody.height===null,'invalid Height neutral');const step=snap().state.step;$('[data-next]').click();assert(snap().state.step===step,'invalid form blocks next');input('height','');await settle();assert(viewer().appliedHeight===0&&$('[data-bmi]').textContent==='','empty Height neutral/BMI empty');input('height',180);await settle();
 for(const field of keys){input(field,9999);await settle();assert(viewer().currentWeights[field]===0&&$('#bv-'+field).getAttribute('aria-invalid')==='true','invalid measurement neutral '+field);input(field,'');await settle();assert(viewer().currentWeights[field]===0,'empty measurement '+field);}
 input('weight',9999);$('[data-next]').click();assert(snap().state.step===0,'invalid Weight still blocks form');input('weight',80);input('height',180);$('[data-next]').click();assert(snap().state.step===1,'valid next to goal');const base=baselinesAtHeight(viewer().currentWeights.height);input('hip',base.hips+profiles.hip.max-profiles.hip.base);await settle();$('[data-next]').click();await settle();assert(viewer().mode==='compare'&&close(viewer().goalWeights.hip,1)&&viewer().currentWeights.hip===0,'current/goal independent');assert(close(viewer().goalWeights.height,viewer().currentWeights.height),'Height retained in goal/compare');$('[data-next]').click();assert(snap().state.step===3,'fitness step navigation');$('[name="bv-goal"][value="1"]').click();assert(snap().state.selectedGoal===1&&!$('.bv-recommendation').hidden,'goal selection unchanged');
 $('[data-view="side"]').click();await settle();const camera=viewer().camera,target=viewer().target;await reset();const after=viewer(),g=geometry();report.reset={maxDeviationM:Math.max(...g.points.map((p,i)=>p.distanceTo(baseline.points[i]))),cameraPreserved:JSON.stringify(camera)===JSON.stringify(after.camera)&&JSON.stringify(target)===JSON.stringify(after.target),identityPreserved:JSON.stringify(ids)===JSON.stringify(identity(after)),weights:after.meshes[0].influences};assert(report.reset.maxDeviationM===0&&report.reset.cameraPreserved&&report.reset.identityPreserved&&invariant(),'reset geometry camera lifecycle');assert(after.meshes[0].influences.slice(4).every(w=>w===0),'reset 15 production channels zero');assert(keys.every(k=>snap().state.currentBody[k]===null)&&snap().state.currentBody.height===null,'reset fields neutral');
 for(const phase of ['height','measurement','combined']){const start=performance.now();for(let i=0;i<500;i++){if(phase!=='measurement')input('height',heightInfluenceToCm(.3*Math.sin(i*.1)));if(phase!=='height'){const k=keys[i%7],p=profiles[k],h=viewer().currentWeights.height,b=baselinesAtHeight(h)[p.measurement];input(k,b+(i%2?p.max:p.min)-p.base);}if(i%25===24){await settle();report.stress.push({phase,updates:i+1,memory:viewer().memory,heap:performance.memory?.usedJSHeapSize,ids:identity(viewer()),canvas:viewer().rendererCanvasCount,webglError:viewer().webglError});assert(JSON.stringify(ids)===JSON.stringify(identity(viewer()))&&viewer().rendererCanvasCount===1&&invariant(),'stress resource invariant');}}report.checks.push({name:phase+' 500 updates',pass:true,milliseconds:performance.now()-start});}
 await reset();$('[data-view="front"]').click();await settle();const count=viewer().renderCount;await delay(500);assert(viewer().renderCount===count&&!viewer().pendingFrame,'idle RAF stops');assert(report.stress.every(x=>JSON.stringify(x.memory)===JSON.stringify(initial.memory)),'stable GPU resource allocations');assert(performance.getEntriesByType('resource').filter(x=>x.name.endsWith('male-mpfb-production-morph-v4.glb')).length===1,'v4 loads once');report.final=snap();report.pass=true;window.heightAudit={report,edge,settle,reset,snap};
}catch(error){report.pass=false;report.error=String(error);window.heightAudit={report};}
