const fs=require('fs');const assert=require('node:assert/strict');
const {chromium}=require('C:/Users/cnhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext();await context.addInitScript(()=>{sessionStorage.setItem('reloadPromoClosed','true');window.__frames=0;const raf=window.requestAnimationFrame;window.requestAnimationFrame=callback=>raf(time=>{window.__frames++;callback(time);});});
const page=await context.newPage();const errors=[],externalErrors=[],results=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'){const url=m.location().url||'';(url && !url.startsWith('http://127.0.0.1:4173')?externalErrors:errors).push({message:m.text(),url});}});
const base='http://127.0.0.1:4173';await page.setViewportSize({width:1440,height:1000});await page.goto(base+'/body-visualizer.html');await page.waitForSelector('[data-viewer="ready"]');
assert.equal(await page.locator('h1').count(),1);
await page.locator('.bv-stage').scrollIntoViewIfNeeded();await page.waitForTimeout(500);
const before=await page.locator('.bv-stage').screenshot();await page.locator('#bv-waist').fill('82');await page.waitForTimeout(550);const after=await page.locator('.bv-stage').screenshot();assert(!before.equals(after));results.push('Measurement changes rendered pixels');
await page.locator('#bv-weight').fill('-1');assert.equal(await page.locator('#bv-weight').getAttribute('aria-invalid'),'true');await page.locator('[data-next]').click();assert.equal(await page.locator('[data-step="0"]').getAttribute('aria-current'),'step');
for(const bad of ['','999']){await page.locator('#bv-weight').fill(bad);assert.equal(await page.locator('#bv-weight').getAttribute('aria-invalid'),'true');}
await page.locator('#bv-weight').fill('70');assert.equal(await page.locator('[data-bmi]').textContent(),'25.7');
await page.locator('[data-range="weight"]').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#bv-weight').inputValue(),'70.1');
await page.locator('.bv-gender label').filter({hasText:'Nam'}).click();await page.locator('.bv-advanced > summary').click();await page.locator('#bv-thigh').fill('60');await page.locator('#bv-arm').fill('35');await page.locator('#bv-shoulder').fill('40');
await page.locator('[data-next]').click();assert.equal(await page.locator('#bv-weight').inputValue(),'70.1');await page.locator('#bv-weight').fill('65');await page.locator('#bv-waist').fill('80');
await page.locator('[data-step="0"]').click();assert.equal(await page.locator('#bv-weight').inputValue(),'70.1');assert.equal(await page.locator('#bv-waist').inputValue(),'82.0');await page.locator('[data-step="1"]').click();assert.equal(await page.locator('#bv-weight').inputValue(),'65');
await page.locator('[data-next]').click();assert.match(await page.locator('[data-differences]').textContent(),/70.1.*65/);assert(await page.locator('.bv-split').isVisible());
await page.locator('#bv-split').fill('30');assert.equal(await page.locator('.bv-divider').evaluate(el=>el.style.left),'30%');
for(const mode of ['current','goal','compare']){await page.locator(`[data-mode="${mode}"]`).click();assert.equal(await page.locator(`[data-mode="${mode}"]`).getAttribute('aria-pressed'),'true');}
await page.locator('[data-view="side"]').click();await page.locator('[data-view="back"]').click();await page.locator('[data-view="reset"]').click();
await page.locator('.bv-stage').scrollIntoViewIfNeeded();const box=await page.locator('.bv-stage').boundingBox();const cameraBefore=await page.locator('.bv-stage').screenshot();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+110,box.y+box.height/2+15,{steps:10});await page.mouse.up();await page.waitForTimeout(150);assert(!cameraBefore.equals(await page.locator('.bv-stage').screenshot()));await page.mouse.wheel(0,-150);await page.locator('.bv-stage').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('+');results.push('Validation, sliders, body type, advanced inputs, independent states, split, drag, zoom, keyboard');
await page.locator('[data-next]').click();await page.locator('.bv-goals label').filter({hasText:'Tăng sức mạnh'}).click();assert(await page.locator('.bv-recommendation').isVisible());assert(await page.locator('.bv-conversion').isVisible());assert.equal(await page.locator('[data-contact]').getAttribute('href'),'https://zalo.me/0374432221');assert.equal(await page.locator('.bv-conversion a').nth(1).getAttribute('href'),'about.html#about-register');
await page.locator('[data-reset]').click();await page.getByRole('button',{name:'Hủy',exact:true}).click();assert(await page.locator('.bv-recommendation').isVisible());await page.locator('[data-reset]').click();await page.locator('.bv-reset-dialog').getByRole('button',{name:'Khôi phục',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#bv-weight')?.value==='60');assert(await page.locator('.bv-conversion').isHidden());results.push('Goals, recommendations, existing contact links, reset cancel/confirm');
const layouts=[];for(const width of [1440,1280,1024,768,430,390,375]){await page.setViewportSize({width,height:900});await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(250);const dimensions=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:document.querySelector('canvas').getBoundingClientRect().height}));assert(dimensions.scroll<=width,JSON.stringify(dimensions));layouts.push(dimensions);await page.screenshot({path:`qa/body-visualizer-${width}.png`,fullPage:true});}
await page.locator('.bv-stage').scrollIntoViewIfNeeded();await page.waitForTimeout(600);const frameCount=await page.evaluate(()=>window.__frames);await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>window.__frames),frameCount);results.push('No idle animation loop');
await page.reload();await page.waitForSelector('[data-viewer="ready"]');assert.equal(await page.locator('#bv-weight').inputValue(),'60');
await page.evaluate(()=>document.querySelector('canvas').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await page.waitForSelector('[data-viewer="fallback"]');assert(await page.locator('[data-retry]').isVisible());await page.locator('[data-retry]').click();await page.waitForSelector('[data-viewer="ready"]');results.push('Refresh privacy, context-loss recovery');
const fallback=await context.newPage();await fallback.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl2'?null:get.call(this,type,...args)};});await fallback.goto(base+'/body-visualizer.html');await fallback.waitForSelector('[data-viewer="fallback"]');await fallback.locator('[data-next]').click();await fallback.locator('[data-next]').click();assert(await fallback.locator('[data-differences]').isVisible());await fallback.locator('[data-next]').click();await fallback.locator('.bv-goals label').first().click();assert(await fallback.locator('.bv-conversion').isVisible());await fallback.close();
const missing=await context.newPage();await missing.route('**/scene.js',route=>route.abort());await missing.goto(base+'/body-visualizer.html');await missing.waitForSelector('[data-viewer="fallback"]');await missing.close();results.push('WebGL unavailable and dependency failure preserve flow');
const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await touchContext.addInitScript(()=>sessionStorage.setItem('reloadPromoClosed','true'));const touch=await touchContext.newPage();await touch.goto(base+'/body-visualizer.html');await touch.waitForSelector('[data-viewer="ready"]');await touch.locator('.bv-stage').scrollIntoViewIfNeeded();await touch.waitForTimeout(500);const tb=await touch.locator('.bv-stage').boundingBox(),cdp=await touchContext.newCDPSession(touch),x=tb.x+tb.width/2,y=tb.y+tb.height/2;const touchBefore=await touch.locator('.bv-stage').screenshot();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+50,y:y+10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(150);assert(!touchBefore.equals(await touch.locator('.bv-stage').screenshot()));await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-25,y},{x:x+25,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-50,y},{x:x+50,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touchContext.close();results.push('Mobile touch rotation and pinch gestures');
const requests=[];page.on('request',r=>requests.push(r.url()));await page.goto(base+'/index.html');assert(await page.locator('.bv-teaser a').isVisible());assert(!requests.some(url=>url.includes('/vendor/three/')));await page.locator('.bv-teaser a').click();await page.waitForSelector('[data-viewer="ready"]');results.push('Homepage entry, no homepage Three.js request, route navigation');
assert.deepEqual(errors,[]);fs.writeFileSync('qa/body-visualizer-results.json',JSON.stringify({results,layouts,errors,externalErrors},null,2));console.log(JSON.stringify({results,layouts,errors,externalErrors},null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
