const fs=require('fs'),assert=require('node:assert/strict');const {chromium}=require('C:/Users/cnhan/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'});const p=await b.newPage();await p.addInitScript(()=>sessionStorage.setItem('reloadPromoClosed','true'));const results=[];
for(const width of [1440,1024,834,768,430,375,320]){await p.setViewportSize({width,height:width===320?568:900});for(const file of ['index','about','facilities','services','class-schedule','membership','locations','blog']){await p.goto('http://127.0.0.1:4173/'+file+'.html');await p.evaluate(()=>document.fonts.ready);const height=await p.evaluate(()=>document.body.scrollHeight);let checks=0;for(let y=0;y<height;y+=260){await p.evaluate(y=>window.scrollTo({top:y,behavior:'instant'}),y);await p.waitForTimeout(35);const overlap=await p.evaluate(()=>{
 const contact=document.querySelector('.floating-contact');if(getComputedStyle(contact).visibility==='hidden')return [];
 const a=contact.querySelector('button').getBoundingClientRect();const overlap=r=>r.left<a.right&&r.right>a.left&&r.top<a.bottom&&r.bottom>a.top;
 return [...document.querySelectorAll('footer,.video-preview,main a,main button,main input,main select,main h1,main h2,main h3,main p,main li')].filter(e=>e.getClientRects().length&&!e.closest('dialog:not([open]),[hidden],.sr-only')).filter(e=>{if(e.matches('h1,h2,h3,p,li')){const r=document.createRange();r.selectNodeContents(e);return [...r.getClientRects()].some(overlap);}return overlap(e.getBoundingClientRect());}).map(e=>e.className||e.tagName);
 });assert.deepEqual(overlap,[],`${file} ${width}px scroll ${y}`);checks++;}results.push({file,width,scrollPositions:checks});}
console.log(width+'px: scrolling checks pass on eight pages');}
fs.writeFileSync(__dirname+'/responsive/scrolling.json',JSON.stringify(results,null,2));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
